config/routes.rb
Rails.application.routes.draw do
  # get 'top' => 'homes#top'
  resources :books
  root to: "homes#top"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence:true
  
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render 'index'
    end
  end
  
  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end


  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render 'edit'
  
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    if book.destroy
      flash[:notice] = "Book was successfully destroyed."
      redirect_to books_path
    else
      render :edit
    end
  end
  
  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/views/books/edit.html.erb
<div class="form-error">
 <% if @book.errors.any? %>
  <div class="error-message">
  <%= "errors prohibited this book from being saved" %></br>
  </div>
  <% @book.errors.full_messages.each do |message| %>
   <%= message %></br>
  <% end %>
 <% end %>
</div>


<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}",local:true do |f| %>
<div class="title">
 <h4>Title</h4>
 <%= f.text_field:title %>
</div>
<div class="body">
 <h4>Body</h4>
 <%= f.text_area:body %>
</div>
<div class="tag">
<%= f.submit 'Update Book' %>
  
</div>


<% end %>

<%= link_to "Show",book_path(@book.id) %>
<%= "|" %>
<%= link_to "Back",books_path %>

app/views/books/index.html.erb
<% if flash[:notice] %>
 <p id="notice">
  <%= flash[:notice] %>
 </p>
<% end %>

<h1>Books</h1>
<table>

  <tr>
   <th>Title</th>
   <th>Body</th>
   <th colspan="3">&nbsp</th>
  </tr>

     <% @books.each do |book| %>


  <tr>

   <td><%= book.title %></td>
   <td><%= book.body %></td>
   <td><%= link_to "Show",book_path(book.id) %></td>
   <td><%= link_to "Edit",edit_book_path(book.id) %></td>
   <td><%= link_to "Destroy",book_path(book.id),method: :delete,"data-confirm" => "Are you sure?" %></td>
  </tr>

 <% end %>
</table>

<div class="form-error">
 <% if @book.errors.any? %>
  <div class="error-message">
  <%= "errors prohibited this book from being saved" %></br>
  </div>
  <% @book.errors.full_messages.each do |message| %>
   <%= message %></br>
  <% end %>
 <% end %>
</div>

  <h1>New book</h1>
     <%= form_with model:@book, url:'/books',local:true do |f| %>

  <div class="title">
   <h4>Title</h4>
   <%= f.text_field:title %>
  </div>
  <div class="body">
   <h4>Body</h4>
   <%= f.text_area:body %>
  </div>
 <div>
  <%= f.submit'Create Book' %>
  </div>
<% end %>
 </div>

app/views/books/show.html.erb
<% if flash[:notice] %>
 <p id="notice">
  <%= flash[:notice] %>
 </p>
<% end %>


<div class="show-title">
 <p><strong>Title</strong> ：<%= @book.title %></p>
</div>
<div class="show-body">
 <p><strong>Body</strong> : <%= @book.body %></p>
</div>
<%= link_to "Edit",edit_book_path(@book.id) %>
<%= "|" %>
<%= link_to "Back",books_path %>

app/views/homes/top.html.erb
<!DOCTYPE html>
 <html>
    <head>
        <title>WebCampBackendNew</title>
    </head>
    <body>
    <h1>ようこそ <strong>Bookers</strong> へ！</h1>
    <p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や<br>印象を共有し交換することができます</p>
    <%= link_to "start", books_path %>
    </body>
 </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <% if flash[:notice] %>
    <div class="flash"></div>
    <% end %>
    
    
    <%= yield %>
  </body>
</html>